### ISSUE TITLE
gcc: error: rurouni/fnv1a.c: No such file or director

### ISSUE THREAD

**Issue by xianhuawei** [douban/Kenshin#20]
gcc: error: rurouni/fnv1a.c: No such file or director

**Comment by xianhuawei** [comment]
没找到 rurouni/fnv1a.c 被 .gitignore 了
求解决

**Comment by windreamer** [comment]
` rurouni/fnv1a.c` is generated by ` rurouni/fnv1a.pyx` with Cython.
If you are using `setuptools >= 18.0`, ` rurouni/fnv1a.c` should be auto-generated.

**Comment by windreamer** [comment]
Can we get the full log?

**Comment by zzl0** [comment]
@xianhuawei 如果 README 中所示，需要使用 `python setup.py build_ext --inplace && python setup.py install` 安装 Kenshin。这个问题你是不是已经解决了吗？

**Comment by xianhuawei** [comment]
解决了 pip install -r requirements.txt 前 要先 pip install -U setuptools  。setuptools 版本不够高导致的，这个可以加到README上去
