### ISSUE TITLE
Graphite 集成

### ISSUE THREAD

**Issue by wooparadog** [douban/Kenshin#4]
貌似项目里面没有提供 grpahite 的 storage finders..

**Comment by zzl0** [comment]
@wooparadog 恩，我们内部的 Graphite-web 目前是比较旧的 0.9.10 版本，想升级到 0.9.14 然后把新的放出来。这段时间其他事情耽搁了下，我会尽快弄这边，争取 6 月中旬之前开放出来。

**Comment by zzl0** [comment]
@wooparadog 我把内部的 Graphite-web 放在了我自己的仓库，最新的 Graphite-web 结构变化还挺多，我说一下当时主要的改动：
1. 添加 Kenshin 文件格式 https://github.com/zzl0/Graphite-web-for-review/blob/master/webapp/graphite/storage.py#L341
2. 添加 fvn1a https://github.com/zzl0/Graphite-web-for-review/blob/master/webapp/graphite/render/hashing.py#L88
3. 我们只在获取高精度数据时读缓存 https://github.com/zzl0/Graphite-web-for-review/blob/master/webapp/graphite/render/datalib.py#L229 ，这样可以防止低精度数据中间一块没有数据。

**Comment by wooparadog** [comment]
Thanks!!!!!!!

**Comment by iandyh** [comment]
It would be nice to have an English tutorial on how to setup Graphite and Kenshin...
